name: "Build and push to GHCR.io"

on:
  workflow_dispatch:

jobs:
  Building:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      name: "Build images"
      env:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.repository }}:latest

      steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Github
        uses: docker/login-action@v1.14.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images to GHCR.io
        uses: docker/build-push-action@v2.9.0
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
